# Generated by Django 3.1.7 on 2021-05-13 02:49

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='body',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='image',
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='image_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='image_capture',
            field=models.ImageField(null=True, upload_to=api.models.upload_location),
        ),
        migrations.AddField(
            model_name='patient',
            name='image_upload',
            field=models.ImageField(null=True, upload_to=api.models.upload_location),
        ),
        migrations.AddField(
            model_name='patient',
            name='visitReason',
            field=models.TextField(null=True),
        ),
    ]
