# Generated by Django 3.1.7 on 2021-05-16 21:22

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210513_0449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50)),
                ('visitReason', models.TextField(null=True)),
                ('consent', models.BooleanField(default=False)),
                ('image_capture', models.ImageField(null=True, upload_to=api.models.upload_location)),
                ('image_upload', models.ImageField(null=True, upload_to=api.models.upload_location)),
                ('image_age', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
