# Generated by Django 3.1.7 on 2021-05-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210516_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_1',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50),
        ),
    ]
