# Generated by Django 3.1.7 on 2021-05-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_patient_1_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_1',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=50, null=True),
        ),
    ]
