# Generated by Django 3.1.7 on 2021-05-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_patient_1_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_1',
            name='image_upload',
            field=models.ImageField(null=True, upload_to='documents/'),
        ),
    ]
