# Generated by Django 3.1.7 on 2021-05-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210517_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_1',
            name='image_upload',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
