# Generated by Django 3.1.7 on 2021-05-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210517_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_1',
            name='image_upload',
            field=models.ImageField(default='', upload_to='media/'),
        ),
    ]
