# Generated by Django 3.1.7 on 2021-05-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210517_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_1',
            old_name='image_capture',
            new_name='Image_capture',
        ),
        migrations.RemoveField(
            model_name='patient_1',
            name='image_upload',
        ),
        migrations.AddField(
            model_name='patient_1',
            name='Image_upload',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
