# Generated by Django 3.1.7 on 2021-05-17 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210517_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_1',
            old_name='Image_capture',
            new_name='image_capture',
        ),
        migrations.RenameField(
            model_name='patient_1',
            old_name='Image_upload',
            new_name='image_upload',
        ),
    ]
