# Generated by Django 3.1.7 on 2021-05-20 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210517_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_1',
            old_name='image_capture',
            new_name='captured_image',
        ),
    ]
