# Generated by Django 3.1.7 on 2021-05-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210520_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_1',
            name='captured_image',
            field=models.ImageField(null=True, upload_to='media/camera'),
        ),
    ]
