# Generated by Django 3.1.7 on 2021-06-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210520_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_1',
            name='age',
        ),
        migrations.AddField(
            model_name='patient_1',
            name='birthdate',
            field=models.DateField(null=True),
        ),
    ]
