# Generated by Django 3.1.7 on 2021-06-01 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210602_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_1',
            name='image_age',
        ),
    ]
