# Generated by Django 3.1.7 on 2021-06-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_patient_1_image_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_1',
            name='nationality',
            field=models.CharField(choices=[('Chinese', 'chinese'), ('Other Nation', 'other nation')], max_length=50, null=True),
        ),
    ]
