# Generated by Django 3.1.7 on 2021-07-08 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_patient_1_nationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_1',
            name='image_upload',
        ),
        migrations.CreateModel(
            name='PatientImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_upload', models.ImageField(null=True, upload_to='media/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient_1')),
            ],
        ),
    ]
