# Generated by Django 3.1.7 on 2021-07-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210708_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientimage',
            name='image_upload',
            field=models.ImageField(null=True, upload_to='Patient Images/'),
        ),
    ]
