# Generated by Django 3.1.7 on 2021-07-11 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210709_2338'),
    ]

    operations = [
    ]
