# Generated by Django 3.1.7 on 2021-07-11 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210711_1213'),
    ]

    operations = [
    ]
