# Generated by Django 3.1.7 on 2021-07-11 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210711_1218'),
    ]

    operations = [
    ]
