# Generated by Django 3.1.7 on 2021-07-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210711_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordata',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
