# Generated by Django 3.1.7 on 2021-07-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20210711_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctordata',
            old_name='first_name',
            new_name='User_name',
        ),
        migrations.RemoveField(
            model_name='doctordata',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='doctordata',
            name='last_name',
        ),
        migrations.AddField(
            model_name='doctordata',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='doctordata',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='doctordata',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
