# Generated by Django 3.1.7 on 2021-07-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20210713_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordata',
            name='User_name',
        ),
        migrations.AddField(
            model_name='doctordata',
            name='user_name',
            field=models.CharField(default='Doctor Name', max_length=50, unique=True),
        ),
    ]
