# Generated by Django 3.1.7 on 2021-07-13 16:47

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20210713_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelManagers(
            name='doctordata',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
