# Generated by Django 3.1.7 on 2021-07-15 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20210713_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportresult',
            name='patient',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.patient_1'),
        ),
    ]
