# Generated by Django 3.1.7 on 2021-07-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20210718_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_1',
            name='captured_image',
            field=models.CharField(max_length=100000000, null=True),
        ),
    ]
